import type { Core } from '@strapi/strapi';

export default {
  register({ strapi }: { strapi: Core.Strapi }) {},

  async bootstrap({ strapi }: { strapi: Core.Strapi }) {
    await runProvisioningBootstrap(strapi);
  },
};

/**
 * Runs once on first boot when PROVISIONING_CALLBACK_URL is set.
 * Creates an admin user + full-access API token, then notifies the
 * central Next.js app so it can store the token on the Team record.
 *
 * Skipped on subsequent restarts if an admin user already exists.
 */
async function runProvisioningBootstrap(strapi: Core.Strapi) {
  const callbackUrl = process.env.PROVISIONING_CALLBACK_URL;
  const teamId = process.env.PROVISIONING_TEAM_ID;

  if (!callbackUrl || !teamId) return; // not a provisioned instance

  // Guard: skip if already bootstrapped (admin user exists)
  const adminCount = await strapi.db.query('admin::user').count({});
  if (adminCount > 0) {
    console.log('[bootstrap] Admin already exists, skipping provisioning.');
    return;
  }

  console.log('[bootstrap] First boot detected — provisioning admin + API token...');

  try {
    // 1. Create admin user
    const adminEmail = `admin@strapi-${teamId}.internal`;
    const adminPassword = require('crypto').randomBytes(24).toString('hex');

    const adminUser = await strapi.service('admin::user').create({
      firstname: 'Admin',
      lastname: 'Strapi',
      email: adminEmail,
      password: adminPassword,
      isActive: true,
      roles: [],
    });

    // Assign super admin role
    const superAdminRole = await strapi.service('admin::role').getSuperAdmin();
    await strapi.service('admin::user').updateById(adminUser.id, {
      roles: [superAdminRole.id],
    });

    // 2. Create full-access API token
    const tokenResult = await strapi.service('admin::api-token').create({
      name: 'dashboard-token',
      description: 'Generated by provisioning bootstrap',
      type: 'full-access',
      lifespan: null, // never expires
    });

    // 3. Notify the central app
    const response = await fetch(callbackUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-provisioning-secret': process.env.PROVISIONING_SECRET ?? '',
      },
      body: JSON.stringify({
        teamId,
        strapiToken: tokenResult.accessKey,
      }),
    });

    if (!response.ok) {
      console.error('[bootstrap] Callback failed:', response.status, await response.text());
    } else {
      console.log('[bootstrap] Provisioning complete — token sent to central app.');
    }
  } catch (err) {
    console.error('[bootstrap] Provisioning error:', err);
  }
}
