import type { Core } from '@strapi/strapi';
import { runThemeScopeMigration } from './migrations/theme-scope';
import { dropPageTemplateKeyGlobalUnique } from './migrations/page-template-key';
import { runImageFormatBackfill } from './migrations/image-format-backfill';

export default {
  register({ strapi }: { strapi: Core.Strapi }) {},

  async bootstrap({ strapi }: { strapi: Core.Strapi }) {
    // Drop the legacy uid global-unique index on page_templates.key BEFORE any
    // content creation, so a second theme's `homepage` can be written (MT-01 /
    // dev-theme homepage provisioning). (theme,key) uniqueness lives in the
    // page-template lifecycle hook, not a DB index.
    await dropPageTemplateKeyGlobalUnique(strapi);
    await runProvisioningBootstrap(strapi);
    // Runs on EVERY boot, unlike runProvisioningBootstrap (first-boot only), so
    // tenants provisioned before the form builder existed self-heal on their next
    // deploy. See the function's header for why this can't live on the platform.
    await ensureFormIngestToken(strapi);
    await ensureDefaultContent(strapi);
    await runThemeScopeMigration(strapi);
    await runImageFormatBackfill(strapi);
  },
};

/**
 * Runs once on first boot when PROVISIONING_CALLBACK_URL is set.
 * Creates an admin user + full-access API token, then notifies the
 * central Next.js app so it can store the token on the Team record.
 *
 * Skipped on subsequent restarts if an admin user already exists.
 */
async function runProvisioningBootstrap(strapi: Core.Strapi) {
  const callbackUrl = process.env.PROVISIONING_CALLBACK_URL;
  const teamId = process.env.PROVISIONING_TEAM_ID;

  if (!callbackUrl || !teamId) return; // not a provisioned instance

  // Guard: skip if already bootstrapped (admin user exists)
  const adminCount = await strapi.db.query('admin::user').count({});
  if (adminCount > 0) {
    console.log('[bootstrap] Admin already exists, skipping provisioning.');
    return;
  }

  console.log('[bootstrap] First boot detected — provisioning admin + API token...');

  try {
    // 1. Create admin user
    const adminEmail = `admin@strapi-${teamId}.internal`;
    const adminPassword = require('crypto').randomBytes(24).toString('hex');

    const adminUser = await strapi.service('admin::user').create({
      firstname: 'Admin',
      lastname: 'Strapi',
      email: adminEmail,
      password: adminPassword,
      isActive: true,
      roles: [],
    });

    // Assign super admin role
    const superAdminRole = await strapi.service('admin::role').getSuperAdmin();
    await strapi.service('admin::user').updateById(adminUser.id, {
      roles: [superAdminRole.id],
    });

    // 2. Create full-access API token (server-side: used by the platform for
    //    privileged customize reads/writes — must NEVER reach the client bundle).
    const tokenResult = await strapi.service('admin::api-token').create({
      name: 'dashboard-token',
      description: 'Generated by provisioning bootstrap',
      type: 'full-access',
      lifespan: null, // never expires
    });

    // 2b. Create a read-only API token (PIPE-05): this is the ONLY token the
    //     platform bakes into the public client bundle (NEXT_PUBLIC_STRAPI_TOKEN).
    //     It is content-scoped read-only, so extracting it from the public bundle
    //     cannot grant write/admin access. POSTed alongside the full-access token.
    const readOnlyResult = await strapi.service('admin::api-token').create({
      name: 'public-readonly-token',
      description: 'Read-only token for the public client bundle (provisioning bootstrap)',
      type: 'read-only',
      lifespan: null, // never expires
    });

    // 3. Notify the central app
    const response = await fetch(callbackUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-provisioning-secret': process.env.PROVISIONING_SECRET ?? '',
      },
      body: JSON.stringify({
        teamId,
        strapiToken: tokenResult.accessKey,
        strapiPublicToken: readOnlyResult.accessKey,
      }),
    });

    if (!response.ok) {
      console.error('[bootstrap] Callback failed:', response.status, await response.text());
    } else {
      console.log('[bootstrap] Provisioning complete — token sent to central app.');
    }
  } catch (err) {
    console.error('[bootstrap] Provisioning error:', err);
  }
}

/** Name of the create-only token the tenant site's form ingest route runs as. */
const FORM_INGEST_TOKEN_NAME = 'form-ingest-token';

/**
 * The narrow permission set the ingest token is allowed to exercise. Deliberately
 * NOT read: the tenant site already holds the read-only public token for loading
 * the form definition it validates against, so this token needs no read grant.
 */
const FORM_INGEST_PERMISSIONS = [
  'api::form-submission.form-submission.create',
  'plugin::upload.content-api.upload',
  // Read on Form is REQUIRED to write a submission, which is not obvious.
  // A FormSubmission carries a `form` relation, and Strapi's validateInput runs
  // `throwRestrictedRelations(auth)` over the request BODY: a relation pointing
  // at a content type the token cannot reach is rejected with
  // `ValidationError: Invalid key form`. Without these two the ingest route's
  // POST /api/form-submissions fails 400 for EVERY submission.
  //
  // This does not widen what is public. A tenant site already reads form
  // definitions with `NEXT_PUBLIC_STRAPI_TOKEN`, which ships inside the public
  // client bundle — form definitions are world-readable on a tenant site today.
  // The token stays create-only for WRITES, which is the property that matters.
  'api::form.form.find',
  'api::form.form.findOne',
];

/**
 * Mint the form-ingest API token and hand it to the platform.
 *
 * WHY THIS LIVES HERE AND NOT ON THE PLATFORM
 * Creating an API token is an ADMIN route (`admin::isAuthenticatedAdmin` on
 * POST /admin/api-tokens) and requires an admin JWT. The platform only ever
 * receives API tokens — the bootstrap admin's password is random and discarded,
 * never sent in the callback — so the platform physically cannot mint this. The
 * self-healing therefore runs inside each tenant's own Strapi.
 *
 * WHY EVERY BOOT, NOT FIRST BOOT
 * runProvisioningBootstrap returns early once an admin user exists, so tenants
 * provisioned before the form builder shipped would never get a token. This runs
 * unconditionally and is idempotent via a name lookup, so every existing tenant
 * self-heals on its next deploy — and the CD pipeline already redeploys every
 * tenant Strapi on a push to main.
 *
 * WHY IT REVOKES ON CALLBACK FAILURE
 * `accessKey` is returned only at creation; afterwards Strapi stores it hashed and
 * it can never be read back. If the token were kept after a failed callback, the
 * name lookup would skip creation forever and the platform would be permanently
 * without a key it can't recover. Revoking on failure keeps the next boot retryable.
 *
 * Degrades quietly: a tenant without this token simply can't accept submissions.
 * Unlike the read-only public token (SEC-02, fail-closed), a missing ingest token
 * leaks nothing, so it must never block a boot or a deploy.
 */
async function ensureFormIngestToken(strapi: Core.Strapi) {
  const callbackUrl = process.env.PROVISIONING_CALLBACK_URL;
  const teamId = process.env.PROVISIONING_TEAM_ID;

  if (!callbackUrl || !teamId) return; // not a provisioned instance (e.g. local dev)

  try {
    const existing = await strapi.service('admin::api-token').getByName(FORM_INGEST_TOKEN_NAME);
    if (existing) {
      // A token's permissions are fixed at CREATION, so a tenant minted before
      // `api::form.form.*` was added above keeps a token that can never write a
      // submission. Returning early here (what this used to do unconditionally)
      // would strand every such tenant forever.
      //
      // Healed with `update` rather than revoke-and-recreate on purpose: update
      // preserves the access key, so the copy the platform already holds stays
      // valid — no second callback, no re-deploy of the tenant site, and no
      // window where the site holds a revoked token. Every existing tenant
      // repairs itself on its next boot.
      const current: string[] = existing.permissions ?? [];
      const missing = FORM_INGEST_PERMISSIONS.filter((p) => !current.includes(p));
      if (missing.length === 0) return; // already minted, delivered and current

      await strapi.service('admin::api-token').update(existing.id, {
        permissions: FORM_INGEST_PERMISSIONS,
      });
      console.log(
        '[bootstrap] Form-ingest token permissions healed, added:',
        missing.join(', ')
      );
      return;
    }

    console.log('[bootstrap] Minting form-ingest token...');

    const ingestResult = await strapi.service('admin::api-token').create({
      name: FORM_INGEST_TOKEN_NAME,
      description: 'Create-only token for public form submissions (tenant site ingest route)',
      type: 'custom',
      permissions: FORM_INGEST_PERMISSIONS,
      lifespan: null, // never expires
    });

    const response = await fetch(callbackUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-provisioning-secret': process.env.PROVISIONING_SECRET ?? '',
      },
      body: JSON.stringify({
        teamId,
        strapiFormToken: ingestResult.accessKey,
      }),
    });

    if (!response.ok) {
      // Roll back so the next boot can retry — see header.
      await strapi.service('admin::api-token').revoke(ingestResult.id);
      console.error(
        '[bootstrap] Form-ingest callback failed, token revoked for retry:',
        response.status,
        await response.text()
      );
      return;
    }

    console.log('[bootstrap] Form-ingest token delivered to central app.');
  } catch (err) {
    // Never block boot — forms degrade, everything else keeps working.
    console.error('[bootstrap] Form-ingest token error:', err);
  }
}

/**
 * Ensures default content exists (homepage template + page).
 * Runs on every boot — safe to call repeatedly (idempotent).
 */
async function ensureDefaultContent(strapi: Core.Strapi) {
  try {
    // Check if any page template exists
    const templateCount = await strapi.db
      .query('api::page-template.page-template')
      .count({});

    if (templateCount > 0) return; // content already exists

    console.log('[bootstrap] No page templates found — creating default homepage...');

    // Create the default homepage template (published)
    const template = await strapi.documents('api::page-template.page-template').create({
      data: {
        name: 'Homepage',
        key: 'homepage',
        description: 'Default homepage template',
        isDefault: true,
        sections: [],
      },
      status: 'published',
    });

    // Create a homepage page linked to the template (published)
    await strapi.documents('api::page.page').create({
      data: {
        title: 'Homepage',
        slug: 'homepage',
        isHomepage: true,
        page_template: [template.documentId],
      },
      status: 'published',
    });

    console.log('[bootstrap] Default homepage template and page created.');
  } catch (err) {
    console.error('[bootstrap] Failed to create default content:', err);
  }
}
