import type { Core } from '@strapi/strapi';
import { runThemeScopeMigration } from './migrations/theme-scope';
import { dropPageTemplateKeyGlobalUnique } from './migrations/page-template-key';
import { runImageFormatBackfill } from './migrations/image-format-backfill';

export default {
  register({ strapi }: { strapi: Core.Strapi }) {},

  async bootstrap({ strapi }: { strapi: Core.Strapi }) {
    // Drop the legacy uid global-unique index on page_templates.key BEFORE any
    // content creation, so a second theme's `homepage` can be written (MT-01 /
    // dev-theme homepage provisioning). (theme,key) uniqueness lives in the
    // page-template lifecycle hook, not a DB index.
    await dropPageTemplateKeyGlobalUnique(strapi);
    await runProvisioningBootstrap(strapi);
    await ensureDefaultContent(strapi);
    await runThemeScopeMigration(strapi);
    await runImageFormatBackfill(strapi);
  },
};

/**
 * Runs once on first boot when PROVISIONING_CALLBACK_URL is set.
 * Creates an admin user + full-access API token, then notifies the
 * central Next.js app so it can store the token on the Team record.
 *
 * Skipped on subsequent restarts if an admin user already exists.
 */
async function runProvisioningBootstrap(strapi: Core.Strapi) {
  const callbackUrl = process.env.PROVISIONING_CALLBACK_URL;
  const teamId = process.env.PROVISIONING_TEAM_ID;

  if (!callbackUrl || !teamId) return; // not a provisioned instance

  // Guard: skip if already bootstrapped (admin user exists)
  const adminCount = await strapi.db.query('admin::user').count({});
  if (adminCount > 0) {
    console.log('[bootstrap] Admin already exists, skipping provisioning.');
    return;
  }

  console.log('[bootstrap] First boot detected — provisioning admin + API token...');

  try {
    // 1. Create admin user
    const adminEmail = `admin@strapi-${teamId}.internal`;
    const adminPassword = require('crypto').randomBytes(24).toString('hex');

    const adminUser = await strapi.service('admin::user').create({
      firstname: 'Admin',
      lastname: 'Strapi',
      email: adminEmail,
      password: adminPassword,
      isActive: true,
      roles: [],
    });

    // Assign super admin role
    const superAdminRole = await strapi.service('admin::role').getSuperAdmin();
    await strapi.service('admin::user').updateById(adminUser.id, {
      roles: [superAdminRole.id],
    });

    // 2. Create full-access API token (server-side: used by the platform for
    //    privileged customize reads/writes — must NEVER reach the client bundle).
    const tokenResult = await strapi.service('admin::api-token').create({
      name: 'dashboard-token',
      description: 'Generated by provisioning bootstrap',
      type: 'full-access',
      lifespan: null, // never expires
    });

    // 2b. Create a read-only API token (PIPE-05): this is the ONLY token the
    //     platform bakes into the public client bundle (NEXT_PUBLIC_STRAPI_TOKEN).
    //     It is content-scoped read-only, so extracting it from the public bundle
    //     cannot grant write/admin access. POSTed alongside the full-access token.
    const readOnlyResult = await strapi.service('admin::api-token').create({
      name: 'public-readonly-token',
      description: 'Read-only token for the public client bundle (provisioning bootstrap)',
      type: 'read-only',
      lifespan: null, // never expires
    });

    // 3. Notify the central app
    const response = await fetch(callbackUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-provisioning-secret': process.env.PROVISIONING_SECRET ?? '',
      },
      body: JSON.stringify({
        teamId,
        strapiToken: tokenResult.accessKey,
        strapiPublicToken: readOnlyResult.accessKey,
      }),
    });

    if (!response.ok) {
      console.error('[bootstrap] Callback failed:', response.status, await response.text());
    } else {
      console.log('[bootstrap] Provisioning complete — token sent to central app.');
    }
  } catch (err) {
    console.error('[bootstrap] Provisioning error:', err);
  }
}

/**
 * Ensures default content exists (homepage template + page).
 * Runs on every boot — safe to call repeatedly (idempotent).
 */
async function ensureDefaultContent(strapi: Core.Strapi) {
  try {
    // Check if any page template exists
    const templateCount = await strapi.db
      .query('api::page-template.page-template')
      .count({});

    if (templateCount > 0) return; // content already exists

    console.log('[bootstrap] No page templates found — creating default homepage...');

    // Create the default homepage template (published)
    const template = await strapi.documents('api::page-template.page-template').create({
      data: {
        name: 'Homepage',
        key: 'homepage',
        description: 'Default homepage template',
        isDefault: true,
        sections: [],
      },
      status: 'published',
    });

    // Create a homepage page linked to the template (published)
    await strapi.documents('api::page.page').create({
      data: {
        title: 'Homepage',
        slug: 'homepage',
        isHomepage: true,
        page_template: [template.documentId],
      },
      status: 'published',
    });

    console.log('[bootstrap] Default homepage template and page created.');
  } catch (err) {
    console.error('[bootstrap] Failed to create default content:', err);
  }
}
